global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["ecom-stack-nginx-exporter-1:9113"]

  - job_name: "backends"
    static_configs:
      - targets:
          - "order:4000"
          - "reco:5000"
          - "inventory:8000"

  - job_name: "prometheus"
    static_configs: [{ targets: ["prometheus:9090"] }]
